#!/bin/bash

mkdir holdme
if ! [ -x /home/dev/.local/bin/black ]; then pip install black; fi
mv rpc/migrations/000[234]*py holdme
rm rpc/migrations/0001_initial.py
sed -i 's/("rpc", "0001_initial"),/#("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
./manage.py makemigrations
black rpc
# need to appply black before proceeding or the seds here are broken
sed -i 's/#("rpc", "0001_initial"),/("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
sed -i 's/("datatracker", "0003_document_intended_std_level")/("datatracker", "0001_initial")/' rpc/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2024, All Rights Reserved/' rpc/migrations/0001_initial.py
mv holdme/*py rpc/migrations/
black rpc
rm -r holdme
