# Generated by Django 4.2.8 on 2023-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('a48_id', models.IntegerField()),
                ('name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120, null=True)),
                ('approved', models.CharField(max_length=3)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'approvals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=50, null=True, unique=True)),
                ('area_acronym', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=10, null=True)),
                ('area_status', models.CharField(max_length=6)),
                ('area_director_name', models.CharField(db_collation='utf8mb4_general_ci', db_column='AREA_DIRECTOR_NAME', max_length=200)),
                ('area_director_email', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='AREA_DIRECTOR_EMAIL', max_length=200, null=True)),
                ('area_web_page', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='AREA_WEB_PAGE', max_length=200, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_area', models.IntegerField()),
                ('fk_index', models.IntegerField()),
            ],
            options={
                'db_table': 'area_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auth48S',
            fields=[
                ('a48_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_column='doc-id', max_length=10, unique=True)),
                ('status', models.CharField(max_length=9)),
                ('start_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('awaiting_ad_approval', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'auth48s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('entry_key', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=10)),
                ('draft_base', models.CharField(max_length=200, unique=True)),
                ('anchored', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'clusters',
                'db_table_comment': 'The draft_base cannot be a FOREIGN KEY on index.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditorAssignments',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=2)),
                ('role_key', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editor_assignments',
                'db_table_comment': 'Allow users to override editor validations so no initials FK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditorRoles',
            fields=[
                ('role_key', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=3)),
                ('role_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'editor_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('ed_key', models.AutoField(primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('assignable', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'editors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Errata',
            fields=[
                ('errata_id', models.AutoField(primary_key=True, serialize=False)),
                ('rs_code', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=3, null=True)),
                ('doc_id', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='doc-id', max_length=10, null=True)),
                ('status_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('conv_format_check', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=3, null=True)),
                ('section', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('orig_text', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('correct_text', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=80, null=True)),
                ('submitter_email', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120, null=True)),
                ('notes', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('submit_date', models.DateField()),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('verifier_id', models.IntegerField(blank=True, null=True)),
                ('verifier_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=80, null=True)),
                ('verifier_email', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=120, null=True)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(db_collation='utf8mb4_general_ci', max_length=100)),
            ],
            options={
                'db_table': 'errata',
                'db_table_comment': 'rs_code is tag to aid correcting converted CGI records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrataLog',
            fields=[
                ('elog_id', models.AutoField(primary_key=True, serialize=False)),
                ('errata_id', models.IntegerField()),
                ('verifier_id', models.IntegerField(blank=True, null=True)),
                ('verifier_name', models.CharField(blank=True, max_length=80, null=True)),
                ('status_id', models.IntegerField()),
                ('doc_id', models.CharField(db_column='doc-id', max_length=10)),
                ('type_id', models.IntegerField()),
                ('section', models.TextField(blank=True, null=True)),
                ('orig_text', models.TextField(blank=True, null=True)),
                ('correct_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('edit_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'errata_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrataStatusCodes',
            fields=[
                ('errata_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('errata_status_code', models.CharField(max_length=40)),
                ('errata_status_text', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'errata_status_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrataTypeCodes',
            fields=[
                ('errata_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('errata_type_code', models.CharField(max_length=10)),
                ('errata_type_helptext', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'errata_type_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('internal_key', models.AutoField(primary_key=True, serialize=False)),
                ('draft', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='DRAFT', max_length=200, null=True)),
                ('date_received', models.DateField(blank=True, db_column='DATE_RECEIVED', null=True)),
                ('time_out_date', models.DateField(blank=True, db_column='TIME-OUT-DATE', null=True)),
                ('expedite_need_date', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='EXPEDITE_NEED_DATE', max_length=10, null=True)),
                ('iesg_approved', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='IESG_APPROVED', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=3, null=True)),
                ('doc_id', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='DOC-ID', max_length=10, null=True)),
                ('title', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='TITLE', null=True)),
                ('authors', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='AUTHORS', max_length=300, null=True)),
                ('format', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='FORMAT', max_length=100, null=True)),
                ('char_count', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='CHAR-COUNT', max_length=50, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, db_column='PAGE-COUNT', null=True)),
                ('pub_status', models.CharField(blank=True, db_column='PUB-STATUS', max_length=21, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=21, null=True)),
                ('email', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='EMAIL', null=True)),
                ('source', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='SOURCE', max_length=100, null=True)),
                ('doc_shepherd', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='DOC_SHEPHERD', max_length=100, null=True)),
                ('iesg_contact', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='IESG_CONTACT', max_length=100, null=True)),
                ('abstract', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='ABSTRACT', null=True)),
                ('pub_date', models.DateField(blank=True, db_column='PUB-DATE', null=True)),
                ('nroffed', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='NROFFED', max_length=50, null=True)),
                ('keywords', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='KEYWORDS', null=True)),
                ('organization', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='ORGANIZATION', null=True)),
                ('queries', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='QUERIES', max_length=50, null=True)),
                ('last_query', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='LAST-QUERY', max_length=50, null=True)),
                ('responses', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='RESPONSES', max_length=100, null=True)),
                ('last_response', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='LAST-RESPONSE', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='NOTES', null=True)),
                ('obsoletes', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='OBSOLETES', max_length=250, null=True)),
                ('obsoleted_by', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='OBSOLETED-BY', max_length=250, null=True)),
                ('updates', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='UPDATES', max_length=760, null=True)),
                ('updated_by', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='UPDATED-BY', max_length=250, null=True)),
                ('see_also', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='SEE-ALSO', max_length=100, null=True)),
                ('see_also_title', models.TextField(blank=True, db_collation='utf8mb4_general_ci', db_column='SEE-ALSO-TITLE', null=True)),
                ('ref', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='REF', max_length=600, null=True)),
                ('ref_flag', models.IntegerField()),
                ('iana_flag', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('generation_number', models.IntegerField()),
                ('consensus_bit', models.CharField(blank=True, max_length=3, null=True)),
                ('xml_file', models.IntegerField()),
                ('doi', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='DOI', max_length=50, null=True)),
                ('sub_page_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_int_key', models.IntegerField()),
                ('op_notes', models.TextField()),
            ],
            options={
                'db_table': 'op_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSources',
            fields=[
                ('rs_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rs_description', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'db_table': 'report_sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RpcRfcstatesummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_iana_flag', models.IntegerField(blank=True, null=True)),
                ('old_ref_flag', models.IntegerField(blank=True, null=True)),
                ('old_version_number', models.IntegerField(blank=True, null=True)),
                ('iana_flag', models.IntegerField(blank=True, null=True)),
                ('ref_flag', models.IntegerField(blank=True, null=True)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('days', models.PositiveSmallIntegerField()),
                ('oldstate_id', models.IntegerField(blank=True, null=True)),
                ('rfc_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rpc_rfcstatesummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RpcStatebydate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField()),
                ('page_count', models.PositiveIntegerField()),
                ('state_id', models.IntegerField()),
                ('doc_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'rpc_statebydate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_number', models.CharField(max_length=7)),
                ('wg_acronym', models.CharField(blank=True, max_length=20, null=True)),
                ('draft_string', models.CharField(blank=True, max_length=100, null=True)),
                ('wg_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'source_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_dockey', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('in_date', models.DateField()),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('iana_flag', models.IntegerField()),
                ('ref_flag', models.IntegerField()),
                ('generation_number', models.IntegerField()),
            ],
            options={
                'db_table': 'state_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_key', models.IntegerField()),
                ('weeks_in_state', models.DecimalField(decimal_places=1, max_digits=10)),
                ('report_date', models.DateField()),
                ('week_of_year', models.IntegerField()),
            ],
            options={
                'db_table': 'statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusChanges',
            fields=[
                ('dockey', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_change', models.DateField(blank=True, null=True)),
                ('url_of_change', models.TextField(blank=True, db_column='URL_of_change', null=True)),
            ],
            options={
                'db_table': 'status_changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StreamSpecificParties',
            fields=[
                ('ssp_id', models.AutoField(primary_key=True, serialize=False)),
                ('stream_name', models.CharField(blank=True, max_length=126, null=True)),
                ('ssp_name', models.CharField(blank=True, max_length=126, null=True)),
                ('ssp_email', models.CharField(max_length=126)),
                ('ssp_webpage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'stream_specific_parties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_column='doc-id', max_length=10)),
                ('draft', models.CharField(max_length=200)),
                ('sub_page_count', models.IntegerField()),
            ],
            options={
                'db_table': 'subcounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestPagecountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_column='DOC-ID', max_length=10)),
                ('draft_name', models.CharField(db_column='DRAFT-NAME', max_length=180)),
                ('draft_version', models.CharField(db_column='DRAFT-VERSION', max_length=20)),
                ('page_count', models.CharField(db_column='PAGE-COUNT', max_length=50)),
            ],
            options={
                'db_table': 'test_pagecount_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verifiers',
            fields=[
                ('verifier_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssp_id', models.IntegerField()),
                ('login_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'verifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('wg_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=50, null=True)),
                ('wg_acronym', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=15, null=True)),
                ('wg_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
                ('ssp_id', models.IntegerField()),
                ('wg_chair_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wg_chair_email', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=200, null=True)),
                ('wg_email', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=80, null=True)),
                ('wg_status', models.CharField(max_length=5)),
                ('other_areas', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
            ],
            options={
                'db_table': 'working_group',
                'managed': False,
            },
        ),
    ]
