# Generated by Django 4.2.6 on 2023-10-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatatrackerPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datatracker_id",
                    models.BigIntegerField(
                        help_text="ID of the Person in the datatracker", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datatracker_id", models.BigIntegerField(unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of draft", max_length=255, unique=True
                    ),
                ),
                ("rev", models.CharField(help_text="Revision of draft", max_length=16)),
                ("title", models.CharField(help_text="Title of draft", max_length=255)),
                (
                    "stream",
                    models.CharField(help_text="Stream of draft", max_length=32),
                ),
                (
                    "pages",
                    models.PositiveSmallIntegerField(help_text="Number of pages"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datatracker.document",
                    ),
                ),
            ],
        ),
    ]
