# Generated by Django 4.2.5 on 2023-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0005_label_actionholder_deadline_and_more'),
        ('datatracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(to='rpc.label'),
        ),
    ]
