# Generated by Django 4.2.6 on 2023-10-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datatracker", "0001_initial"),
        ("rpc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlabel",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rpc.label"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="labels",
            field=models.ManyToManyField(
                through="datatracker.DocumentLabel", to="rpc.label"
            ),
        ),
    ]
