# Generated by Django 4.2.5 on 2023-09-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0005_label_rfctobelabel_actionholder_deadline_and_more'),
        ('datatracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatracker.document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpc.label')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(through='datatracker.DocumentLabel', to='rpc.label'),
        ),
    ]
