# Generated by Django 5.1 on 2024-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shepherd',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='source_format',
            field=models.CharField(help_text='Draft source file format', max_length=16),
            preserve_default=False,
        ),
    ]
