# Generated by Django 5.1.1 on 2024-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intended_std_level',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
