# Generated by Django 4.2.5 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatatrackerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(help_text="Datatracker's subject ID for this Person", max_length=255, unique=True)),
                ('plain_name', models.CharField(blank=True, help_text="Datatracker's plain name for this Person", max_length=255)),
            ],
        ),
    ]
