# Generated by Django 4.2.5 on 2023-09-18 14:03

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datatracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositionName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpcRole',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFormatName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StdLevelName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TlpBoilerplateChoiceName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnusableRfcNumber',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RpcPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveSmallIntegerField(default=40)),
                ('can_hold_role', models.ManyToManyField(to='rpc.rpcrole')),
                ('capable_of', models.ManyToManyField(to='rpc.capability')),
                ('datatracker_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datatracker.datatrackerperson')),
                ('manager', models.ForeignKey(limit_choices_to={'can_hold_role__slug': 'manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_people', to='rpc.rpcperson')),
            ],
        ),
        migrations.CreateModel(
            name='RfcToBe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_april_first_rfc', models.BooleanField(default=False)),
                ('rfc_number', models.PositiveIntegerField(null=True)),
                ('order_in_cluster', models.PositiveSmallIntegerField(default=1)),
                ('external_deadline', models.DateTimeField(null=True)),
                ('internal_goal', models.DateTimeField(null=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpc.cluster')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpc.dispositionname')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='datatracker.document')),
                ('intended_boilerplate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.tlpboilerplatechoicename')),
                ('intended_std_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.stdlevelname')),
                ('intended_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.streamname')),
                ('submitted_boilerplate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.tlpboilerplatechoicename')),
                ('submitted_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpc.sourceformatname')),
                ('submitted_std_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.stdlevelname')),
                ('submitted_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rpc.streamname')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rfctobe',
            constraint=models.CheckConstraint(check=models.Q(('draft__isnull', False), ('is_april_first_rfc', True), _connector='XOR'), name='rfctobe_draft_not_null_xor_is_april_first_rfc', violation_error_message='draft must be null if and only if is_april_first_rfc'),
        ),
        migrations.AddConstraint(
            model_name='rfctobe',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('cluster', 'order_in_cluster'), name='rfctobe_unique_order_in_cluster', violation_error_message='order in cluster must be unique'),
        ),
    ]
