# Generated by Django 4.2.5 on 2023-09-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatracker', '0001_initial'),
        ('rpc', '0004_populate_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('is_exception', models.BooleanField(default=False)),
                ('color', models.CharField(default='#FF0000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='RfcToBeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='actionholder',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='actionholder',
            name='target_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actionholder_set', to='datatracker.document'),
        ),
        migrations.AddField(
            model_name='actionholder',
            name='target_rfctobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actionholder_set', to='rpc.rfctobe'),
        ),
        migrations.AddConstraint(
            model_name='actionholder',
            constraint=models.CheckConstraint(check=models.Q(('target_document__isnull', True), ('target_rfctobe__isnull', True), _connector='XOR'), name='actionholder_exactly_one_target', violation_error_message='exactly one target field must be set'),
        ),
        migrations.AddField(
            model_name='rfctobelabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpc.label'),
        ),
        migrations.AddField(
            model_name='rfctobelabel',
            name='rfctobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpc.rfctobe'),
        ),
        migrations.AddField(
            model_name='rfctobe',
            name='labels',
            field=models.ManyToManyField(through='rpc.RfcToBeLabel', to='rpc.label'),
        ),
    ]
